#using docker-compose to create a minecraft server
services:
#creating a minecraft server
  minecraft:
    image: minecraft:latest
    tty: true
    stdin_open: true
    container_name: minecraft
#setting the ports
    ports:
      - "28990:28990"
#setting the environment variables
    environment:
      EULA: "TRUE"
      MEMORY: "2G"
      MAX:MEMORY: "6G"
#creating a volume to store the mods, world, server.properties and logs
    volumes:
      - ./Mods/:/Minecraft/mods
      - ./Mundo/:/Minecraft/Thaumcraft
      - ./config/server.properties:/Minecraft/server.properties
      - ./logs/:/Minecraft/logs
    networks:
         minecraft:
            aliases:
            - minecraft

#creating a playit server
  playit:
    image: playit:latest
    tty: true
    stdin_open: true
    container_name: playit
    networks:
        minecraft:
          aliases:
            - playit
networks:
  minecraft:
    name: minecraft