#using docker-compose to create a minecraft server
services:
#creating a minecraft server
  minecraft:
    image: minecraft:latest
    tty: true
    stdin_open: true
    container_name: minecraft
#setting the ports
    ports:
      - "19890:19890"
#setting the environment variables
    environment:
      EULA: "TRUE"
      MEMORY: "2G"
      MAX:MEMORY: "6G"
#creating a volume to store the mods, world, server.properties and logs
    volumes:
      - ./MCDATA/1.12.2/Mods/:/Minecraft/mods
      - ./MCDATA/1.12.2/Mundo/:/Minecraft/Thaumcraft
      - ./MCDATA/1.12.2/config/server.properties:/Minecraft/server.properties
      - ./MCDATA/1.12.2/logs/:/Minecraft/logs
